[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.8.18"
  PIP_CACHE_DIR = ".pip-cache"
  PIP_NO_CACHE_DIR = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse" 