[build]
  command = "npm install && npm run build"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9.18"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse" 