services:
  - type: web
    name: rainbow-qr-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free 